### ISSUE TITLE
Feature Request Upgrade

### ISSUE THREAD

**Issue by djpimp2010** [GenesisGateway/genesis.js#16]
I am working on an integration with a genesis API, using ApplePay.

The documentation says the method of overriding a Terminal ID is to import the config file and update the variable.

We cannot do this, as under high volume, with users using Apple Pay / Google Pay / 3DS, each payment request would set the global customer token for the Terminal ID, and it would affect other transactions.

To avoid this, I have forked the repo and made a tweak, this seems to work fine, and can now pass in a Terminal ID along with the request data.

(I've made another tweak too, which helps our audit system, so not worth me doing a PR for this simple code snippet.)

It would be awesome if you could roll this out globally to all of your methods please.

Thanks!

![Screenshot 2024-04-11 at 13 49 53](https://github.com/GenesisGateway/genesis.js/assets/2423623/5b7b8cec-53cd-4cb6-9714-c667d73c5031)

**Comment by dyd** [comment]
Hello @djpimp2010 

I think that there is no need for such a tweak.

Check [here](https://github.com/GenesisGateway/genesis.js?tab=readme-ov-file#configuration).

**Comment by djpimp2010** [comment]
Hi @dyd 

When the node server loads, it loads the config object into memory.
This single config object is referenced by all of the transaction types.

If you need to send different transaction types to a different terminal, you cannot just override the global config object, because under a high traffic situation, where 10x payments may happen within a few seconds, there is no continuity.

A payment request may change the global config object to update the terminal, but before its reached the next part of the program, to then process the transaction request, a different payment request has already set the global config object to a different terminal ID.

There is no protection against a condition like that, on a per-transactional basis, where each transaction type has to set its own terminal ID.

This will cause big problems under high traffic.

**Comment by dyd** [comment]
Hi @djpimp2010,

OK. I got it. We will think about it.

Thank you for your report!

**Comment by dyd** [comment]
Hi @djpimp2010 ,

you can check https://github.com/GenesisGateway/genesis.js/releases/tag/3.2.0. We have a Manual [configuration](https://github.com/GenesisGateway/genesis.js/tree/3.2.0?tab=readme-ov-file#configuration) there.
